#!/bin/bash

# Ensure system is up to date
apt-get update

# Ensure required packages are installed
puppet resource package git ensure=present
puppet resource package apache2 ensure=present

# Ensure Apache2 service is running
puppet resource service apache2 ensure=running

# Clean and recreate working directory
puppet resource file /operate/9558696j ensure=absent force=true
puppet resource file /operate/9558696j ensure=directory

# Clone the repo
cd /operate/9558696j
git clone https://github.com/Fauziku2/9558696j-op-repo.git

# Replace index.html
cp -p /operate/9558696j/9558696j-op-repo/index-op-9558696j.html /var/www/html/index.html

